apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.nginx }}
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.app }}
        args:
          - "{{ .Values.args }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
          - configMapRef:
              name: flux-app-one-helm-chart-config-map-from-env-file
              optional: true
