apiVersion: v1
kind: Service
metadata:
  name: flux-app-one-component-service
spec:
  selector:
    app: flux-app-one-component
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5678
  type: LoadBalancer
