apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app-one-component-deployment
  labels:
    app: flux-app-one-component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-app-one-component
  template:
    metadata:
      labels:
        app: flux-app-one-component
    spec:
      containers:
      - name: flux-app-one-component
        image: hashicorp/http-echo
        args:
          - "-text=Hello [2] [component], Kubernetes!"
        ports:
        - containerPort: 5678
        envFrom:
          - configMapRef:
              name: flux-app-one-config-map-from-env-file
              optional: true
