apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app-one-deployment
  labels:
    app: flux-app-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flux-app-one
  template:
    metadata:
      labels:
        app: flux-app-one
    spec:
      containers:
      - name: nginx
        image: nginx
      - name: flux-app-one
        image: hashicorp/http-echo
        args:
          - "-text=Hello [overlay test] [ deploy-flux-cluster-two ] [ final overlay ], Kubernetes!"
        ports:
        - containerPort: 5678
        envFrom:
          - configMapRef:
              name: flux-app-one-config-map-from-env-file
              optional: true
