apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-app-one
replicas:
- count: 5
  name: flux-app-one-deployment
images:
- name: nginx
  newTag: stable-alpine
namespace: flux-app-one-cluster-two
labels:
- includeSelectors: true
  pairs:
    env: cluster-two
    just-a-common-label: any-common-label-value
commonAnnotations:
  just-a-common-annotation: any-common-annotation-value
  source: flux-cd-training
configMapGenerator:
- envs:
  - config_map_file.env
  name: flux-app-one-config-map-from-env-file
resources:
- ../../deploy/flux-app-one
patches:
- path: flux-app-one-deployment.yaml
- path: flux-app-one-service.yaml
