apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-app-one
replicas:
- count: 5
  name: flux-app-one-deployment
resources:
- ../../deploy/flux-app-one
patches:
- path: flux-app-one-deployment.yaml
- path: flux-app-one-service.yaml
