apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-app-one
replicas:
- count: 5
  name: flux-app-one-deployment
images:
- name: nginx
  newTag: stable-alpine
namespace: flux-app-one-cluster-two
commonLabels:
 env: cluster-two
 just-a-common-label: any-common-label-value
commonAnnotations:
 source: flux-cd-training
 just-a-common-annotation: any-common-annotation-value
resources:
- ../../deploy/flux-app-one
patches:
- path: flux-app-one-deployment.yaml
- path: flux-app-one-service.yaml
