apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-app-one

- count: 2
  name: flux-app-one-deployment

labels:
- includeSelectors: true
  pairs:
    env: cluster-two
    just-a-common-label: any-common-label-value
commonAnnotations:
  just-a-common-annotation: any-common-annotation-value
  source: flux-cd-training

configMapGenerator:
- envs:
  - config_map_file.env
  name: flux-app-one-config-map-from-env-file

resources:
- flux-app-one-deployment.yaml
- flux-app-one-service.yaml
